# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 18:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a2g2_dj', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mol',
            new_name='ChemThing',
        ),
    ]
