# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-04 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flow',
            name='status',
            field=models.CharField(choices=[('PENDING', 'pending'), ('RUNNING', 'running'), ('COMPLETED', 'completed'), ('FAILED', 'failed')], default='PENDING', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='data',
            field=models.TextField(default='{}', null=True),
        ),
    ]
