# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 18:02
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_spec',
            field=jsonfield.fields.JSONField(blank=True, default=dict, null=True),
        ),
    ]
