# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0002_auto_20170505_1802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flowjob',
            name='flow',
        ),
        migrations.RemoveField(
            model_name='flowjob',
            name='job',
        ),
        migrations.RemoveField(
            model_name='flow',
            name='spec',
        ),
        migrations.RemoveField(
            model_name='job',
            name='error',
        ),
        migrations.RemoveField(
            model_name='job',
            name='name',
        ),
        migrations.AddField(
            model_name='job',
            name='label',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.DeleteModel(
            name='FlowJob',
        ),
    ]
