# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 12:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0003_auto_20170509_1254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mission',
            old_name='name',
            new_name='label',
        ),
    ]
