# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-14 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0003_flow_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flow',
            name='label',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
