# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-24 19:54
from __future__ import unicode_literals

from django.db import migrations, models
import django_extensions.db.fields
import missions.models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0004_auto_20170414_2047'),
    ]

    operations = [
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('uuid', models.CharField(default=missions.models.str_uuid4, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('label', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'abstract': False,
                'get_latest_by': 'modified',
            },
        ),
    ]
