# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='error',
            field=models.TextField(blank=True, null=True),
        ),
    ]
