# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 17:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0002_flow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='mission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='missions.Mission'),
        ),
        migrations.AlterField(
            model_name='flow',
            name='mission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='missions.Mission'),
        ),
    ]
