# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0004_flowrunner'),
    ]

    operations = [
        migrations.AddField(
            model_name='flow',
            name='finished',
            field=models.NullBooleanField(),
        ),
    ]
