# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 14:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_auto_20161130_1447'),
        ('missions', '0005_workflow_finished'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowJob',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('finished', models.NullBooleanField(default=False)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.Job')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='missions.Workflow')),
            ],
            options={
                'get_latest_by': 'modified',
                'ordering': ('-modified', '-created'),
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='WorkflowRunner',
        ),
        migrations.AddField(
            model_name='workflow',
            name='jobs',
            field=models.ManyToManyField(through='missions.WorkflowJob', to='jobs.Job'),
        ),
    ]
