# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0007_auto_20161130_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowrunner',
            name='path',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
