# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0008_workflowrunner_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowrunner',
            name='error',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
