# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-02 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0009_flowrunner_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowjob',
            name='json_serialization',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='flowrunner',
            name='json_serialization',
            field=models.TextField(null=True),
        ),
    ]
