# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-02 19:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0010_auto_20161202_1911'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FlowRunner',
            new_name='FlowSpec',
        ),
    ]
