# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-02 19:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0011_auto_20161202_1911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflow',
            name='runner_key',
        ),
        migrations.AddField(
            model_name='workflow',
            name='spec',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='missions.WorkflowSpec'),
        ),
    ]
