# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-02 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0012_auto_20161202_1912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflowjob',
            name='json_serialization',
        ),
        migrations.AddField(
            model_name='workflow',
            name='json_serialization',
            field=models.TextField(null=True),
        ),
    ]
