# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-02 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0013_auto_20161202_1913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='mission',
        ),
        migrations.RenameField(
            model_name='flow',
            old_name='json_serialization',
            new_name='serialization',
        ),
        migrations.RenameField(
            model_name='flowspec',
            old_name='json_serialization',
            new_name='serialization',
        ),
        migrations.RemoveField(
            model_name='flow',
            name='finished',
        ),
        migrations.RemoveField(
            model_name='flow',
            name='jobs',
        ),
        migrations.AddField(
            model_name='flow',
            name='status',
            field=models.CharField(choices=[('Pending', 'pending'), ('Running', 'running'), ('Completed', 'completed')], default='Pending', max_length=32, null=True),
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
