# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-06 17:55
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0014_auto_20161202_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowjob',
            name='meta',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
