# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-20 13:30
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0015_workflowjob_meta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflow',
            name='spec',
        ),
        migrations.AlterField(
            model_name='mission',
            name='uuid',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=64, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='uuid',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=64, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='workflowjob',
            name='uuid',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=64, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='WorkflowSpec',
        ),
    ]
