# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-20 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0016_auto_20161220_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='flow',
            name='claimed',
            field=models.NullBooleanField(default=False),
        ),
    ]
