# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-16 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('UNCLAIMED', 'unclaimed')], max_length=32, null=True),
        ),
    ]
