# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 18:34
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('PENDING', 'pending'), ('CLAIMED', 'claimed')], default='PENDING', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='uuid',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=32, primary_key=True, serialize=False),
        ),
    ]
