# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 18:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0004_workflowrunner'),
        ('jobs', '0004_auto_20161122_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='workflow',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='missions.Workflow'),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('Pending', 'pending'), ('Claimed', 'claimed'), ('Completed', 'completed')], default='Pending', max_length=32, null=True),
        ),
    ]
