# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 18:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_auto_20161129_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='finished',
            field=models.NullBooleanField(editable=False),
        ),
        migrations.AlterField(
            model_name='job',
            name='flow',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='missions.Flow'),
        ),
    ]
