# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_auto_20161129_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='type',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
