# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_auto_20161205_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='claimed',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('PENDING', 'pending'), ('RUNNING', 'running'), ('COMPLETED', 'completed')], default='PENDING', max_length=32, null=True),
        ),
    ]
