# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 16:36
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_auto_20170118_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
