# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_job_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='data',
            field=models.TextField(null=True),
        ),
    ]
