# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 21:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_auto_20170130_1638'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='spec',
            new_name='job_spec',
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('PENDING', 'pending'), ('RUNNING', 'running'), ('COMPLETED', 'completed'), ('FAILED', 'failed')], default='PENDING', max_length=32, null=True),
        ),
    ]
