# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 12:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import jsonfield.fields
import taggit.managers
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChemThing',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('uuid', models.CharField(default=uuid.uuid4, max_length=64, primary_key=True, serialize=False)),
                ('keys', jsonfield.fields.JSONField(default=dict, null=True)),
                ('types', jsonfield.fields.JSONField(default=dict, null=True)),
                ('props', jsonfield.fields.JSONField(default=dict, null=True)),
                ('precursors', jsonfield.fields.JSONField(default=dict, null=True)),
                ('ancestors', jsonfield.fields.JSONField(default=dict, null=True)),
            ],
            options={
                'get_latest_by': 'modified',
                'ordering': ('-modified', '-created'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TaggedChemThing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a2g2_dj.ChemThing')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='a2g2_dj_taggedchemthing_items', to='taggit.Tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='chemthing',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='a2g2_dj.TaggedChemThing', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
