# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-04 16:41
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a2g2_dj', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chemthing',
            name='precursors',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
