# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-04 13:30
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a2g2_dj', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chemthing',
            name='cml',
        ),
        migrations.AddField(
            model_name='chemthing',
            name='types',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=128), null=True, size=None),
        ),
    ]
