# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-14 20:47
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a2g2_dj', '0003_auto_20170413_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemthing',
            name='precursors',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='chemthing',
            name='props',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='chemthing',
            name='types',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, null=True),
        ),
    ]
